#!/usr/bin/env pwsh
# verify.ps1 - repo-real verification for fitness-tracker (generated by ai-workflows/bootstrap-repo). ASCII-only.
# Runs ONLY supported, non-destructive checks; never installs/deploys/serves/mutates data. -Quick skips build.
[CmdletBinding()]
param([switch]$Quick)
$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $repoRoot
$script:failed = @()
function Invoke-Check { param([string]$Name, [string[]]$NpmArgs) Write-Host ""; Write-Host "=== $Name ===" -ForegroundColor Cyan; & npm @NpmArgs; if ($LASTEXITCODE -ne 0) { $script:failed += $Name; Write-Host "FAILED: $Name" -ForegroundColor Red } else { Write-Host "OK: $Name" -ForegroundColor Green } }
function Invoke-Cargo { param([string]$Name, [string[]]$Args, [string]$Wd) if (-not (Get-Command cargo -ErrorAction SilentlyContinue)) { Write-Host "=== $Name === SKIPPED: cargo not found" -ForegroundColor Yellow; return }; Push-Location (Join-Path $repoRoot $Wd); try { & cargo @Args; $c = $LASTEXITCODE } finally { Pop-Location }; if ($c -ne 0) { $script:failed += $Name } else { Write-Host "OK: $Name" -ForegroundColor Green } }
function Invoke-Shell { param([string]$Name, [string]$Cmd) Write-Host "=== $Name ==="; iex $Cmd; if ($LASTEXITCODE -ne 0) { $script:failed += $Name } else { Write-Host "OK: $Name" -ForegroundColor Green } }
function Invoke-Compose { Write-Host "=== compose config ==="; if (Get-Command docker -ErrorAction SilentlyContinue) { & docker compose config --quiet; if ($LASTEXITCODE -ne 0) { $script:failed += 'compose config' } else { Write-Host 'OK: compose config' -ForegroundColor Green } } else { Write-Host 'SKIPPED: docker not found' -ForegroundColor Yellow } }
Invoke-Check 'lint' @('run','lint')
Invoke-Check 'typecheck' @('run','typecheck')
Invoke-Check 'test' @('test')
Invoke-Check 'build' @('run','build')
Invoke-Compose

if ($script:failed.Count -gt 0) { Write-Host ""; Write-Host "FAILED: $($script:failed -join ', ')" -ForegroundColor Red; exit 1 }
Write-Host ""; Write-Host "All required checks passed." -ForegroundColor Green; exit 0