#!/usr/bin/env bash
# verify.sh - repo-real verification for fitness-tracker (generated by ai-workflows/bootstrap-repo).
set -uo pipefail
cd "$(dirname "$0")/.."
failed=()
check() { local n="$1"; shift; echo "=== $n ==="; if npm "$@"; then echo "OK: $n"; else failed+=("$n"); fi; }
cargo_check() { local n="$1"; shift; command -v cargo >/dev/null 2>&1 || { echo "SKIP $n (no cargo)"; return; }; if cargo $@; then echo "OK: $n"; else failed+=("$n"); fi; }
shell() { local n="$1"; shift; echo "=== $n ==="; if "$@"; then echo "OK: $n"; else failed+=("$n"); fi; }
compose_config() { command -v docker >/dev/null 2>&1 && { docker compose config --quiet && echo 'OK: compose' || failed+=('compose'); } || echo 'SKIP: no docker'; }
check 'lint' run lint
check 'typecheck' run typecheck
check test test
check 'build' run build
compose_config

[ ${#failed[@]} -gt 0 ] && { echo "FAILED: ${failed[*]}"; exit 1; } || { echo "All required checks passed."; exit 0; }